### ISSUE TITLE
Function `_get_source` doesn't work in the python console of PyCharm

### ISSUE THREAD

**Issue by sjrl** [lf1-io/padl#44]
If I try running the following in the python console in PyCharm
```python
from lf import lf
lf.trans(lambda x: x)
```
I get the error 
```python
Traceback (most recent call last):
  File "/Users/sebastianlee/Aleph-One-Gmbh/lf/lf/lf.py", line 204, in _wrap_lambda
    full_source = caller_frame.f_globals['_lf_source']
KeyError: '_lf_source'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/Users/sebastianlee/Aleph-One-Gmbh/lf/lf/lf.py", line 62, in _get_source
    return ''.join(linecache.cache[filename][2])
KeyError: '<input>'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/sebastianlee/Aleph-One-Gmbh/lf/lf/lf.py", line 250, in trans
    return _wrap_lambda(fun_or_cls)
  File "/Users/sebastianlee/Aleph-One-Gmbh/lf/lf/lf.py", line 206, in _wrap_lambda
    full_source = _get_source(caller_frame.f_code.co_filename)
  File "/Users/sebastianlee/Aleph-One-Gmbh/lf/lf/lf.py", line 65, in _get_source
    with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '<input>'
```

**Comment by sjrl** [comment]
This works with the current version of PADL, with no changes required.
